### ISSUE TITLE
关于服务器迁移

### ISSUE THREAD

**Issue by Rratic** [JuliaRoadmap/zh#18]
> <https://discourse.juliacn.com/t/topic/7376>

@johnnychen94 
可能需要更新 `secrets.MIRROR_SERVER_USERNAME`、`secrets.MIRROR_SERVER_SSH_KEY`、`builddocs.yml : jobs.build.steps.with.target` 及服务器那边的配置

我不是很了解你们这个服务器内部的情况，您看看？

**Comment by johnnychen94** [comment]
@Rratic 我这边麻烦社区的另一位朋友 @HaoxuanGuo 来负责部署，刚才将他加入到这个仓库的 admin 了
