### ISSUE TITLE
如何构建？

### ISSUE THREAD

**Issue by johnnychen94** [JuliaRoadmap/zh#3]
没找到构建整个文档的方法...

**Comment by Rratic** [comment]
不太清楚您的意思
现在我用的是隔壁的HTMLify仓库，用generate函数导出（当前功能还不全）

**Comment by HackYardo** [comment]
这个HTMLify包没在Github里？能搜出来但不是用julia写的…是指的py库？

**Comment by Rratic** [comment]
@HackYardo 
确定没看到 https://github.com/JuliaRoadmap/htmlify ？

**Comment by HackYardo** [comment]
我能够理解用库的话会受其所限，有时候不如自己造轮子，但是如果他/她人想要为此项目做贡献，却不知道怎么用htmlify来构建，没文档没栗子没docstring，那还怎么贡献，还得看htmlify的源码？而且这源码不合规呀，说好了用四个空格，不用tab的。
之前想的是写个"某某某.md"就可以请求拉取了，现在怎么感觉挺复杂的 😱

**Comment by Rratic** [comment]
我似乎提到过**htmlify**没有做好现在基本上只有我知道怎么用，我想等做好了再写文档
> 之前想的是写个"某某某.md"就可以请求拉取了

难道不是这样吗？
htmlify是用来把一堆markdown转成一堆html的工具

**Comment by Rratic** [comment]
@johnnychen94 
我在隔壁 https://github.com/JuliaRoadmap/htmlify 的README写了相关信息
每周还是每月、解析到 啥.juliacn.com 请服务器管理者（~~是你吗~~）决定

**Comment by Rratic** [comment]
P.S. 建议先不在主页放链接

**Comment by johnnychen94** [comment]
可能因为我所理解的构建方式和你所设想的不太一样，我还是没太搞明白该如何构建。

```julia
git clone https://github.com/JuliaRoadmap/zh.git
cd zh
git clone https://github.com/JuliaRoadmap/htmlify.git
julia -e 'include("htmlify/src/manage.jl"); generate(".", "build")'
```

```julia
ERROR: IOError: open("svg", 0, 0): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:97 [inlined]
 [2] open(path::String, flags::UInt8, mode::Int64)
   @ Base.Filesystem ./filesystem.jl:105
 [3] open
   @ ./filesystem.jl:97 [inlined]
 [4] sendfile(src::String, dst::String)
   @ Base.Filesystem ./file.jl:992
 [5] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
   @ Base.Filesystem ./file.jl:384
 [6] generate(srcdir::String, tardir::String)
   @ Main ~/Documents/Julia/JuliaRoadmap/zh/htmlify/src/manage.jl:30
 [7] top-level scope
   @ none:1
```

---

>> 之前想的是写个"某某某.md"就可以请求拉取了
>
> 难道不是这样吗？
> htmlify是用来把一堆markdown转成一堆html的工具

从贡献者的角度来说会有两点需求：

- 少量修改：快速找到需要修改的源文件的位置 -- 这个我看到了构建的主页上有 "编辑此页面" 的UI，不过似乎跳转的位置还不够精确 --> Documenter 的部署可以直接跳转到对应的 md 文件 （我估计这个修复应该很容易）
- 大量修改：在本地构建和预览，确保格式和内容不出差错 -- 如果是 Documenter 的话，大家都知道可以通过 `include("docs/make.jl")` 文件来构建，但对于初次贡献者来说，这个仓库显得有点不知道该如何下手。

最直接的问题：如何确保 #2  这样的修改是有效的或无效的？在不知道如何构建的情况下，只能是维护者说什么是什么了，甚至也不知道应该如何修改。

从维护者的角度来说也有两点 CI/CD 方面的需求：

- 预览：从维护者的角度来说，直接查看构建的 html 页面是最容易确认构建的格式和内容正确的方法。
- 每次 commit 或 release 都进行一次构建，然后根据规则决定是否部署到服务器上 -- 它不应该是一个每周或者每月的 cron job，换句话说，构建的触发应该发生在 zh 这个仓库有新的 commit 的时候。

目前 zh 仓库是缺少 CI 支持的

**Comment by Rratic** [comment]
@johnnychen94 
> julia -e 'include("htmlify/src/manage.jl"); generate(".", "build")'

啊这，我好像忘了说路径得传绝对路径

**Comment by Rratic** [comment]
> 从维护者的角度来说也有两点 CI/CD 方面的需求：

~~正常来说改的是内容，不会有类似#2的需求~~实际上根据CONTRIBUTING的规范走就不会有问题（这不是复杂的代码，没有这个必要），然后这个开销有点大，~~我不会用CI~~

> 快速找到需要修改的源文件的位置

这个得重构点东西，~~因为这个数据没存~~，一会弄

**Comment by johnnychen94** [comment]
如果可以把相对路径支持一下的话，我可以来写一下 CI 的支持

**Comment by Rratic** [comment]
收到
~~不支持相对路径主要是我滥用`cd`~~

**Comment by Rratic** [comment]
https://github.com/JuliaRoadmap/htmlify/commit/ccae5bd1170622ac1724c46eda6ad9d2282c9a11
